# Generated by Django 2.0.1 on 2018-02-03 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180203_2004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
